### ISSUE TITLE
`breadcrumb_trail` is not intuition

### ISSUE THREAD

**Issue by hiphapis** [piotrmurach/loaf#17]
Just IMHO, `breadcrumb_trail` is not intuition. 
latest name `breadcrumbs` is better then current name
or
`render_breadcrumb` also better and easy
i think `render` is intuition and like rails more then `trail`

**Comment by piotrmurach** [comment]
This is a matter of taste in designing apis. I've chosen `breadcrumb_trail` on purpose to represent the actual behaviour, as the call contains all the breadcrumbs for a given page, commonly referred to as breadcrumb trail. The `render_breadcrumb` would suggest that something is being rendered where in actual fact, nothing is, there is no html generated and as such it wouldn't fit. The `rails` word doesn't work in the context of English language, breadcrumb trail is a set phrase, I've never heard anyone make breadcrumb rails reference, have you?

**Comment by hiphapis** [comment]
I mean, "render ~~~" is code style of rails. anyway i understand what you say
you known, naming is very hard always
