### ISSUE TITLE
How to change default value of 'match'

### ISSUE THREAD

**Issue by hiphapis** [piotrmurach/loaf#18]
For example, `Home / Articles / Title / Edit` this case is use `:exact`
I think usually have this case.
Anyway, I found how to change default match value, and check [configuration](https://github.com/piotrmurach/loaf/blob/master/lib/loaf/configuration.rb)
Unfortunately not support this feature yet

**Comment by piotrmurach** [comment]
If I understand correctly, you wish to add `:match` configuration option to setup default behaviour for breadcrumbs. In that case, please submit PR and ideally a test case to proof implementation.

**Comment by hiphapis** [comment]
That’s what I’m saying ;)
Ok. I'll try when i have time!

**Comment by piotrmurach** [comment]
Released `v0.6.2` with this change. Thanks!
