### ISSUE TITLE
Set self to controller in proc

### ISSUE THREAD

**Issue by brendon** [piotrmurach/loaf#21]
Hi there, I was wondering if you'd consider setting self to be the controller when evaluating `Proc`'s for breadcrumb paths and urls?

```
breadcrumb ->(c) { c.find_article(c.params[:post_id]).title }, :articles_path
```
becomes
```
breadcrumb -> { find_article(params[:post_id]).title }, :articles_path
```

This would be much more succinct. It's similar to how `decent_exposure` does it: https://github.com/hashrocket/decent_exposure#fetch

Seems related to: https://github.com/piotrmurach/loaf/pull/20

**Comment by piotrmurach** [comment]
I'm in favour of this idea!
