### ISSUE TITLE
Quick Fixes :)

### ISSUE THREAD

**Issue by brendon** [piotrmurach/loaf#29]
Hi @piotrmurach, just a couple of things.

- Would you mind correcting my name in the changeling (Bendon), it should read Brendon. Bendon is a brand of bra's in New Zealand! :D The childhood pain is already coming back to me!
- Your changelog links point to the tty-spinner project for some reason. Caused a bit of confusion for a second :)

Thanks for your `0.8` update. It was exactly what I was looking for (regarding truncation).

**Comment by piotrmurach** [comment]
Hi Brrrrrrrrrrrendon,

Thanks for the cultural insight, I do wish to visit New Zealand! I can only image the abuse you got, kids are cruel....

I felt that keeping the breadcrumb formatting complexity away from the library was a good choice.

Do you mind submitting PR with changelog fixes? Essentially you can fix yourself :wink

**Comment by brendon** [comment]
Haha! Definitely come for a visit. I'll shout you lunch :) Nick-names are par for the course here. The trick was to make sure everyone had a sufficiently painful one! :D

I'll put in a PR for you now :)
