### ISSUE TITLE
how to clear or disable the breadcrumb array?

### ISSUE THREAD

**Issue by alphamarket** [piotrmurach/loaf#34]
### The problem description
Let's say I have a mechanism that computes and define some breadcrumb set before the every action execution, but in some actions, I want to reset/ignore the automatically generated breadcrumb set and create (or don't create) the new ones. Is there anything like `breadcrumb_clear()` method or something in the gem? (I couldn't find it the source) 

* OS version: Ubuntu 18.04.1 LTS
* Ruby version: 2.5.0
* Loaf version: 0.8

**Comment by alphamarket** [comment]
It would be nice if a direct read & write access to breadcrumb's array provided.

**Comment by piotrmurach** [comment]
In controller action, you can call `clear_breadcrumbs`, I must've needed that method back in the day. If this works for you the please consider submitting PR with documentation so others can benefit.
