### ISSUE TITLE
How to support standard rails controller with "index > show" pattern

### ISSUE THREAD

**Issue by krsyoung** [piotrmurach/loaf#37]
### Describe the problem
I'm trying to find the best pattern to work with a standard rails controller.  For example, if I have a controller called book `Book` I'd like to have `Books > The World is Flat` where Books is clickable to the `index` method when in the `show` method.

However, the current implementation returns `true` for `crumb.current?` for both the class-level breadcrumb as well as the method level breadcrumb.  Ideally I would not need to include the `books_path` breadcrumd in every member method.

### Steps to reproduce the problem
```
class BooksController < ApplicationController
  breadcrumb 'Books', :books_path

  def show
    breadcrumb @book.title, book_path(@book)
  end
end
```

```
# view
      <% if breadcrumb_trail.any? %>
      <nav aria-label="breadcrumb">
        <ol class='breadcrumb'>
          <% breadcrumb_trail do |crumb| %>
            <li class="breadcrumb-item <%= crumb.current? ? 'active' : '' %>">
              <%= crumb.current? %> <%= link_to_unless crumb.current?, crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>
            </li>
          <% end %>
        </ol>
      </nav>
      <% end %>
```

### Actual behaviour
Neither link is clickable.

### Expected behaviour
I would expect that the class level crumb would always be clickable (for the index method).

### Describe your environment

* OS version: Mac OS
* Ruby version: 2.6.2
* Loaf version: 0.8.1

**Comment by piotrmurach** [comment]
Hi Chris,

Thanks for using the `loaf` gem. I would encourage you to read the section about [matching](https://github.com/piotrmurach/loaf#213-match) request URLs. By default, the `:inclusive` option is used which means both the top level index and show level breadcrumbs are clickable. Please change to, for example, `:exclusive` to match one or the other. And to make sure that the index breadcrumb is always clickable, whether it is current or not, change:

```
<%= link_to_unless crumb.current?, crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>
``` 
to:
```
<%= link_to crumb.name, crumb.url, (crumb.current? ? {'aria-current' => 'page'} : {}) %>
```

**Comment by vicovictor** [comment]
I think this is not solved yet. I am having the same issue:

```
root > index > show
```

Both index and show are linked, and recognized as current. I think this is due to how `match` recognizes it by url/path.

**Comment by vicovictor** [comment]
My bad. Actually by using `match: :exclusive` works:

```
breadcrumb 'Categories', :categories_path, match: :exclusive, only: [:index, :show]
```
