### ISSUE TITLE
Title Integration

### ISSUE THREAD

**Issue by kinduff** [piotrmurach/loaf#40]
### Are you in the right place?
Yes

### Describe the problem
Would love to see title integration or a method that allows to display the breadcrumb as the title of the page. It's completetly unrelated to the purpose of the gem, but a workaround could work too.

```
<title><%= breadcrumb_trail :as_title, default: "Default Title", separator: "|" %></title>
```
```
<title>Children | Parent | Default Title</title>
```

**Comment by piotrmurach** [comment]
Hi Alejandro,

Thanks for giving `loaf` a try. 

This is strictly breadcrumbs handling library. It doesn't try to do more or less. Often the virtue in software is restraint. Many moons ago, I implemented [tytus](https://github.com/piotrmurach/tytus) to do just page titles.

**Comment by kinduff** [comment]
:100: on tytus! Love your work, keep it up!
