### ISSUE TITLE
breadcrumb_trail options has no effect

### ISSUE THREAD

**Issue by molfar** [piotrmurach/loaf#43]
Passing any match options to breadcrumb_trail inside views has no effect.

```
<% breadcrumb_trail match: :exact do |crumb| %>
  <%= link_to_unless crumb.current?, crumb.name, crumb.url, class: 'text-gray-700 underline' %>
  <% unless crumb.current? %><span>::</span><% end %>
<% end %>
```

**Comment by molfar** [comment]
https://github.com/piotrmurach/loaf/blob/6a8d586d3a49b4e524be425dee86d5def8eb79f1/spec/unit/view_extensions/breadcrumb_trail_spec.rb#L237

Changing this line to
`view.breadcrumb_trail(&block)`
or to
`view.breadcrumb_trail(match: : inclusive, &block) # any other valid match value`
does not make test fail

**Comment by piotrmurach** [comment]
Hi! Thanks for this report. This sounds like a bug. Would you have time to submit a fix with a test?

**Comment by molfar** [comment]
I cant catch this bug yet, I arrived to https://github.com/piotrmurach/loaf/blob/6a8d586d3a49b4e524be425dee86d5def8eb79f1/lib/loaf/view_extensions.rb#L90 
This regex works not as expected. It doesn not show that "/" is active within "/posts"
