### ISSUE TITLE
Gem declares dependency on all of Rails

### ISSUE THREAD

**Issue by csutter** [piotrmurach/loaf#44]
### Describe the problem
Thank you so much for this brilliant gem, it's been a real joy to use so far! ❤️ 

I have a suggestion for improvement – at the moment, loaf declares a dependency on the entire `rails` meta-gem in its gemspec: https://github.com/piotrmurach/loaf/blob/master/loaf.gemspec#L28

I usually depend on only the specific parts of Rails that I want to use in an application, but including loaf in the Gemfile means that the rest of Rails (e.g. Action Cable, Active Storage, ...) now comes along for the ride regardless.

I think that the gem should only really need `railties`, `actionpack` and `activesupport`.

I'm happy to look into this and make a PR, but wanted to check first if you agree with this idea before I do!

### Steps to reproduce the problem
Add `loaf` to `Gemfile` of a "slimmed down" Rails project, `bundle install`.

For reference, here are the Rails gems one of my applications includes:

```ruby
RAILS_VERSION = '~> 6.0.3'
gem 'actionpack', RAILS_VERSION
gem 'activemodel', RAILS_VERSION
gem 'activerecord', RAILS_VERSION
gem 'activesupport', RAILS_VERSION
gem 'railties', RAILS_VERSION
```

### Actual behaviour
Installed gems include all Rails subgems:
```
rails (6.0.3.2)
   actioncable (= 6.0.3.2)
   actionmailbox (= 6.0.3.2)
   actionmailer (= 6.0.3.2)
   actionpack (= 6.0.3.2)
   actiontext (= 6.0.3.2)
   actionview (= 6.0.3.2)
   activejob (= 6.0.3.2)
   activemodel (= 6.0.3.2)
   activerecord (= 6.0.3.2)
   activestorage (= 6.0.3.2)
   activesupport (= 6.0.3.2)
   bundler (>= 1.3.0)
   railties (= 6.0.3.2)
   sprockets-rails (>= 2.0.0)
```

### Expected behaviour

No additional gems installed beyond those strictly required for loaf to function.

### Describe your environment

* OS version: any
* Ruby version: 2.7.x
* Loaf version: 0.9.0

**Comment by piotrmurach** [comment]
Hi Christian 👋 

This sounds like a fine idea to me. This is a Rails gem but it doesn't mean we cannot shed some 'dependency weight'. I haven't investigated this but hopefully, the `actionpack` is all that's needed, I'd like to skip `activesupport` as a dependency if possible. 

Looking forward to PR!
